[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build_asteroids]
command = "cargo"
args = [
  "build",
  "--package",
  "asteroids",
  "--manifest-path",
  "asteroids/Cargo.toml",
  "--release",
  "--target",
  "wasm32-unknown-unknown",
]

[tasks.move_asteroids]
script_runner = "@shell"
script = '''
rm -f ./asteroids/public/asteroids.wasm
mv ./target/wasm32-unknown-unknown/release/asteroids.wasm ./asteroids/public/
'''

[tasks.asteroids]
run_task = { name = ["build_asteroids", "move_asteroids"] }
